# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('name', models.TextField()),
                ('venue', models.TextField()),
                ('group', models.TextField()),
                ('rsvp_limit', models.IntegerField()),
                ('status', models.TextField()),
                ('waitlist_count', models.IntegerField()),
                ('yes_rsvp_count', models.IntegerField()),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('visibility', models.TextField()),
                ('created', models.TextField()),
                ('duration', models.TextField()),
                ('time', models.TextField()),
                ('updated', models.TextField()),
                ('utc_offset', models.IntegerField()),
            ],
        ),
    ]
